name: CI
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  test:
    name: test ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [
          windows-latest,
          # macos-latest, # cppfront is currently broken on AppleClang
          ubuntu-latest,
        ]
        include:
          - os: windows-latest
            gen: Visual Studio 17 2022
          - os: ubuntu-latest
            gen: Ninja
    env:
      CMAKE_GENERATOR: ${{ matrix.gen }}
      CMAKE_BUILD_TYPE: Release
      CMAKE_CONFIG_TYPE: Release
      CMAKE_PREFIX_PATH: ${{github.workspace}}/_local
    runs-on: ${{ matrix.os }}
    steps:
      # System set-up
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: lukka/get-cmake@latest

      - name: Install GCC 11
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-11 g++-11
          echo "CC=gcc-11" >> $GITHUB_ENV
          echo "CXX=g++-11" >> $GITHUB_ENV

      # Main cppfront library
      - name: Configure cppfront
        run: cmake -S . -B build/cppfront
      - name: Build cppfront
        run: cmake --build build/cppfront
      - name: Install cppfront locally
        run: cmake --install build/cppfront --prefix _local

      # Regression tests
      - name: Configure regression tests
        run: cmake -S regression-tests -B build/regression-tests 
      - name: Build regression tests
        run: cmake --build build/regression-tests
      - name: Run regression tests
        run: ctest --output-on-failure -j 2
        working-directory: build/regression-tests

      # Example
      - name: Configure example
        run: cmake -S example -B build/example
      - name: Build example
        run: cmake --build build/example
      - name: Run example
        run: ./build/example/main && cmake -E cat xyzzy
